[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# 环境变量配置（需要在Netlify控制台中设置）
# VITE_DEEPSEEK_API_KEY
# VITE_DEEPSEEK_BASE_URL
# VITE_MINIMAX_API_KEY
# VITE_MINIMAX_BASE_URL